language: generic 

sudo: required

service:
  - docker

before_install:
  - docker build -t alaimar/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true alaimar/docker-react npm run test